### PR TITLE
Fix for hiding responsive elements

### PR DESCRIPTION
**Pull request by developher-net**
The classes for hiding elements at different responsive breakpoints are inconsistent.

### CODE REVIEW

**Comment by developher-net** [comment]
The classes included don't make logical sense, and don't work as advertised. This cleans up to simpler states that are easier to understand behavior by class name.

**Comment by bradfrost** [comment]
Thanks for this. These visibility classes were done very much in haste, so thank you so much for taking care of it.

**Comment by foobartel** [comment]
A thought on these fixes: Since the breakpoint variables are called $bp-small etc. wouldn't it make sense to also name the classes .hide-bp-small etc.? In this case names could possibly be shortened to $bp-s, $bp-m, $bp-l-max,  since you always understand what they refer and belong to. Otherwise I would suggest to use 'medium' instead of 'med' for a better naming consistency. Any thoughts?

**Comment by bradfrost** [comment]
Heya,
I wouldn't think too hard about what I have put in here as a default. The
idea is that people are supposed to author things the way they see fit. So
while i appreciate semantics like this, it's sort of beside the point.

The goal is to create a tool that enables people to author code that makes
sense for the project they're working on. It would be heartbreaking to see
people blindly take these defaults and run with them. I'm sure it will
happen, but the focus of this project is the shell rather than the guts.

On Wednesday, June 19, 2013, Holger Bartel wrote:

> A thought on these fixes: Since the breakpoint variables are called
> $bp-small etc. wouldn't it make sense to also name the classes
> .hide-bp-small etc.? In this case names could possibly be shortened to
> $bp-s, $bp-m, $bp-l-max, since you always understand what they refer and
> belong to. Otherwise I would suggest to use 'medium' instead of 'med' for a
> better naming consistency. Any thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradfrost/patternlab/pull/10#issuecomment-19702829
> .

## 

---

Brad Frost
http://bradfrostweb.com
http://twitter.com/brad_frost

**Comment by foobartel** [comment]
Hey, thanks for clarifying and your thoughts on this. I do agree on the shell and guts idea, but it just came to mind and I wanted to mention and discuss. Just as you already said, do that s#^% yourself ;)

**Pull request merged**
